### PR TITLE
Add delete attendance endpoint

### PR DESCRIPTION
**Pull request by thaigillespie**
Add AttendanceController and endpoint to delete attendances, add skeleton code for updating attendances' times, add delete button on frontend to attendance table on event details page, will add that button
for check off table and, in another PR, RSVP table

fsdfdf

IGNORE THE EDIT BUTTON THAT IS JUST THERE FOR ME TO SEE IF BOTH CAN FIT INTO THE ATTENDANCE TABLE

### CODE REVIEW

**Comment by yuw006** [comment]
Do you think that we need maybe a "confirm deletion" modal in case of a misclick? or would that be a bit annoying to the user

**Comment by thaigillespie** [comment]
> 
> 
> Do you think that we need maybe a "confirm deletion" modal in case of a misclick? or would that be a bit annoying to the user

That's a good idea. We have that for event deletion too so I might as well just add it for this

**Comment by thaigillespie** [comment]
Added confirmation modal

**Comment by yuw006** [comment]
looks good to me

**Review by yuw006 — APPROVED** [review]

**Pull request merged**
