### PR TITLE
Repo clean up (part 1)

### PR DESCRIPTION
**Pull request by thaigillespie**

### CODE REVIEW

**Comment by godwinpang** [comment]
@thaigillespie could you cherry pick your commits into a new branch starting at `806d18687976293235a61300b08efad2304a2aac` ? rn your PR includes eric's s3 changes and the old monorepo stuff

**Comment by thaigillespie** [comment]
> 
> 
> @thaigillespie could you cherry pick your commits into a new branch starting at `806d18687976293235a61300b08efad2304a2aac` ? rn your PR includes eric's s3 changes and the old monorepo stuff

what does that commit hash lead to?

**Comment by thaigillespie** [comment]
Will close this after https://github.com/HKN-UCSD/hkn-server/pull/218 gets merged in

**Comment by godwinpang** [comment]
see #218

**Pull request closed without merging**
