### PR TITLE
Attempt to add react-dev-utils/crossSpawn to dependency list

### PR DESCRIPTION
**Pull request by thaigillespie**
Deleted node_modules and package-lock.json, then ran `npm i`. Pushed code after and that didn't work so I ran `npm audit fix` just to see if it would fix this react-dev-utils/crossSpawn issue and it looks like it works?

### CODE REVIEW

**Comment by godwinpang** [comment]
? I only see a removed package-lock

**Comment by thaigillespie** [comment]
> 
> 
> ? I only see a removed package-lock

I added my second attempt, where I just ran npm audit fix lol and it works???

**Comment by thaigillespie** [comment]
But yeah this react-dev-utils/crossSpawn not found thing has been breaking our recent builds and I was trying to find a way to fix it. Very weird bc I thought this was fixed [here](https://github.com/HKN-UCSD/hkn-server/pull/217) already

**Comment by thaigillespie** [comment]
Anyway @godwinpang you think we should merge this in  or what? I'm not sure if this breaks anything but so far tests are passing

**Review by godwinpang — APPROVED** [review]
:shipit:

**Comment by thaigillespie** [comment]
> 
> 
> :shipit:

that is a cool emote lmao

**Pull request merged**
