### PR TITLE
increase default to 20 rows per table page display

### PR DESCRIPTION
**Pull request by audreygao**

### CODE REVIEW

**Comment by godwinpang** [comment]
lgtm - but could you add back the .lock files? we commit those into git

**Comment by audreygao** [comment]
@godwinpang not sure how this happened. I used the version I cloned 2 weeks ago and didn't remove any files, and I used git add --all when I commit the changes. What files exactly do you want me to add?

**Comment by godwinpang** [comment]
@audreygao do u see frontend/package-lock.json and backend/package-lock.json in your local directory?

**Comment by audreygao** [comment]
@godwinpang I just checked. I do have frontend/package-lock.json and backend/package-lock.json in my local directory.

**Comment by thaigillespie** [comment]
I do see the files as well in Audrey's branch. Please pull from master before you merge and resolve any merge conflicts @audreygao since master has the package-lock.json that doesn't break build process on Netlify

**Comment by audreygao** [comment]
@thaigillespie Okay. Will do next time. Sorry for my mistake.

**Comment by thaigillespie** [comment]
> @thaigillespie Okay. Will do next time. Sorry for my mistake.

Oh no it wasn’t your mistake lol, some dependency was missing for whatever reason before your PR, just had to fix that for these tests to pass now!

**Comment by audreygao** [comment]
@thaigillespie Ok, got it!

**Comment by thaigillespie** [comment]
> 
> 
> I do see the files as well in Audrey's branch. Please pull from master before you merge and resolve any merge conflicts @audreygao since master has the package-lock.json that doesn't break build process on Netlify

@audreygao can you do this so we can get this PR merged in?

**Review by thaigillespie — DISMISSED** [review]
lgtm

**Comment by thaigillespie** [comment]
@audreygao you can probably merge master into this branch so that the hotfix I made for backend is in

**Review by thaigillespie — APPROVED** [review]
lgtm, sorry for all the troubles with this PR!

**Pull request merged**
