### PR TITLE
Refactor modals

### PR DESCRIPTION
**Pull request by thaigillespie**
An attempt at making our modal components more readable, usable and DX-friendly

No need to worry about changes to circleci, vscode settings, or backend, focus on the rest of the files, which are on the modal changes

image

image

### CODE REVIEW

**Comment by yuw006** [comment]
looks nice, is there an example of ButtonWithAlertModal?

**Review by yuw006 — APPROVED** [review]
looks good

**Comment by thaigillespie** [comment]
> 
> 
> looks good

Great question. Unfortunately I don't have an example for ButtonWithAlertModal yet. I think that's because I haven't found anything that necessitates the use of ButtonWithAlertModal in our code base _yet_

**Comment by thaigillespie** [comment]
> 
> 
> looks nice, is there an example of ButtonWithAlertModal?

Great question. Unfortunately I don't have an example for ButtonWithAlertModal yet. I think that's because I haven't found anything that necessitates the use of ButtonWithAlertModal in our code base yet

**Pull request merged**
