### PR TITLE
Repo clean up to get rid of unused code and dependencies (part 1)

### PR DESCRIPTION
**Pull request by thaigillespie**

### CODE REVIEW

**Comment by thaigillespie** [comment]
@godwinpang ok so I checked out to master, pulled, made a new branch, reset --hard to the commit hash you gave me, then cherry picked the other 4 commits from the other branch and it still gave me this...

**Comment by godwinpang** [comment]
something doesn't seem right - maybe we can take a look tmrw @thaigillespie

**Comment by thaigillespie** [comment]
Will close this after https://github.com/HKN-UCSD/hkn-server/pull/218 gets merged in

**Comment by godwinpang** [comment]
see #218

**Pull request closed without merging**
