### PR TITLE
Added run_build and run_linter_prettier jobs for CircleCI.

### PR DESCRIPTION
**Pull request by thaigillespie**
run_build executes 'npm run build', while run_linter_prettier
executes 'npm run lint' then 'npx prettier --check ./src/**/*.ts.

run_build is dependent upon run_lint_prettier, in the sense that
run_build can only start if run_lint_prettier succeeds.

### CODE REVIEW

**Comment by godwinpang** [comment]
uh oh looks like prettier isn't being run on some files

**Comment by godwinpang** [comment]
dont think it has anything to do with your changes; just some things from the previous commits

**Comment by thaigillespie** [comment]
yeah lmao I done goofed up

**Comment by godwinpang** [comment]
no I think you're fine - looks like maybe @AneeshJalan doesn't have precommit hooks installed

**Comment by thaigillespie** [comment]
Maybe, but I just ran 'npx prettier --write src/**/*.ts' anyway so should be good

**Comment by thaigillespie** [comment]
This should be done now since I actually ran npx prettier --write :)))

**Comment by godwinpang** [comment]
🔥

**Comment by thaigillespie** [comment]
Should I merge it then or is there anything else I need to cover in this PR?

**Comment by godwinpang** [comment]
mnerge

**Pull request merged**
