### PR TITLE
Add docker-compose.

### PR DESCRIPTION
**Pull request by godwinpang**
This allows for setting up the whole stack locally via a single docker-compose up command.

Add changes to expose npm i and reduce build step.

node_modules are stored in volumes declared in docker-compose.yml,
allowing for reuse between container restarts.

### CODE REVIEW

**Comment by ericke8** [comment]
Looks like I'm having problems with `docker compose up`, I'm getting errors that `no such file exists` when doing the `npm install` step.  Specifically, there are things missing under `/app/node_modules/.staging/[some package file path]`

Also, could you update the README so we know what exactly to run?

Here's a little bit off the end of the error:
```
#10 32.81 npm WARN tar ENOENT: no such file or directory, open '/app/node_modules/.staging/date-fns-317fda1d/esm/endOfTomorrow/index.js'
#10 32.81 npm WARN tar ENOENT: no such file or directory, open '/app/node_modules/.staging/date-fns-317fda1d/esm/endOfWeek/index.js'
#10 32.81 npm WARN tar ENOENT: no such file or directory, open '/app/node_modules/.staging/date-fns-317fda1d/esm/endOfYear/index.js'
#10 32.81 npm WARN tar ENOENT: no such file or directory, open '/app/node_modules/.staging/date-fns-317fda1d/esm/endOfYesterday/index.js'
#10 32.81 npm WARN tar ENOENT: no such file or directory, open '/app/node_modules/.staging/date-fns-317fda1d/esm/format/index.js'
#10 34.27 npm ERR! code ENOENT
#10 34.27 npm ERR! syscall spawn git
#10 34.27 npm ERR! path git
#10 34.27 npm ERR! errno ENOENT
#10 34.27 npm ERR! enoent Error while executing:
#10 34.27 npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/eligrey/FileSaver.js.git
#10 34.27 npm ERR! enoent
#10 34.27 npm ERR! enoent
#10 34.27 npm ERR! enoent spawn git ENOENT
#10 34.27 npm ERR! enoent This is related to npm not being able to find a file.
#10 34.27 npm ERR! enoent
```

**Comment by godwinpang** [comment]
yeah it should just be docker compose up @ericke8 will update doc and take a look

**Comment by godwinpang** [comment]
@ericke8 https://github.com/mbrn/material-table/issues/2109 istg i fixed it

**Comment by godwinpang** [comment]
nvm package-lock.json also breaks

**Review by thaigillespie — APPROVED** [review]
lgtm

**Pull request merged**
