### PR TITLE
Yank attendance stuff to its own AttendanceController from EventController

### PR DESCRIPTION
**Pull request by thaigillespie**
This isn't a big change in terms of backend, but it's a pretty significant change in the perspective of frontend, meaning a decent amount of code on the frontend is gonna break because of this. This means frontend needs to be changed a decent amount after this is merged in (if it is merged in).

### CODE REVIEW

**Comment by godwinpang** [comment]
monorepo when :)

**Comment by thaigillespie** [comment]
Ok trueeee monorepo would help a ton, or at least it would make things more convenient lol

**Review by godwinpang — APPROVED** [review]
just skimmed - lgtm

**Comment by godwinpang** [comment]
don't merge until FE is ready

**Comment by thaigillespie** [comment]
Yep I was thinking of the same thing. I was thinking that this should be merged when I'm ready to work on frontend integration (so before FE is ready). Thoughts?

**Comment by godwinpang** [comment]
monorepo when :)

**Comment by godwinpang** [comment]
@thaigillespie updates?

**Comment by thaigillespie** [comment]
@godwinpang sorry haven't had time to work on this, I finished all the other things tho

**Pull request closed without merging**
